### ISSUE TITLE
This addon fails in fastboot.

### ISSUE THREAD

**Issue by alexmasita** [Matt-Jensen/ember-service-worker-emberfire-messaging#1]
Have installed this addon in my fastboot app which also has the ember-service-worker addon installed and running successfully.  This addon however fails with the following error: 

```
ReferenceError: navigator is not defined
    at Object.initialize (/Users/alexmasita/External/Personal/projects/Ember Apps/mpesa-on-fastboot/tmp/broccoli_merge_trees-output_path-hVF7gRkE.tmp/assets/addon-tree-output/ember-service-worker-emberfire-messaging/instance-initializers/register-firebase-service-worker.js:16:1)
```

On scrutiny of the file as you can see below: It appears the navigator object is not enclosed in a fastboot check.  Could this be the issue?

```
export function initialize(applicationInstance, _navigator) {
  if (!_navigator) _navigator = navigator;  // <=== not enclosed in a fastboot check.
  if (typeof FastBoot === 'undefined' && 'serviceWorker' in _navigator) {
    const firebase = applicationInstance.lookup('service:firebase-app');
    const {
      options = {}
    } = firebase;
    if (!options.messagingSenderId) {
      throw new Error('Please set `firebase: { messagingSenderId }` in your config/environment.js');
    }
    _navigator.serviceWorker.ready.then((reg) =>
      firebase.messaging().useServiceWorker(reg));
  }
}
export default {
  name: 'register-firebase-service-worker',
  initialize
};
```

I  edited the file accordingly and this initializer passes successfully however, I now encounter another error within the services/firebase-message.js  saying `"(....).messaging()"`  is not a function on line 105.

What could be the issue.

Here is my environment:
ember-cli: 2.16.2
node: 8.4.0
os: darwin x64

**Comment by Matt-Jensen** [comment]
I'm checking testing this out now, at the very least I'll be adding a hotfix for Fastboot tests.

**Comment by alexmasita** [comment]
Many thanks for your expeditious response.  I have installed the updated and it still throws the following error within the service:

```
TypeError: get(...).messaging is not a function
    at Class.init (/Users/alexmasita/External/Personal/projects/Ember Apps/mpesa-on-fastboot/tmp/broccoli_merge_trees-output_path-2xVLUBHb.tmp/assets/addon-tree-output/ember-service-worker-emberfire-messaging/services/firebase-message.js:105:1)
```

Could it be we need to enclose the messaging object in a fastboot check?
