### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by tpetrone** [Matt-Jensen/ember-service-worker-emberfire-messaging#10]
Hi! 
Reading the walkthrough installation steps I found two things really odd:

1. `export default default Route.extend({`
2. `firebaseMessage: service(),`

I translated as:

1. export ~default~ default Route.extend({
2. firebaseMessage: ~service~inject(),

**Comment by Matt-Jensen** [comment]
1. Thanks for pointing that out, got that fixed.
2. `import { inject as service } from '@ember/service';` isn't a unpopular convention, however thank you for your perspective on that.
