### ISSUE TITLE
Can't seem to get this working

### ISSUE THREAD

**Issue by lordy1981** [Matt-Jensen/ember-service-worker-emberfire-messaging#11]
Hi, I am new to Ember and firebase, so please be gentle :-) I have followed the instructions to get this configured, and can see my app making a request to https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=<API-KEY>. I have added the requestUserPermission action but when called it never appears to hit the firebaseMessage service and don't get a token. I don't get any errors either, am i missing something?

**Comment by Matt-Jensen** [comment]
Maybe?  It's tough for me to know for sure, can you create a repo with the applicable code?

You don't have to reveal your Firebase credentials or anything, just need to see your application code.
