### ISSUE TITLE
Recommended way to customize the "setBackgroundMessageHandler" in serviceworker/index.js

### ISSUE THREAD

**Issue by alexmasita** [Matt-Jensen/ember-service-worker-emberfire-messaging#5]
Hi Matt,

What would be the recommended approach to customizing the `setBackgroundMessageHandler` callback so I can send an enhanced notification?  I am exploring adding sound, vibration and possibly modify it's notification display length across platforms.

Let me know.

**Comment by Matt-Jensen** [comment]
I think I understand what you're getting at, basically you'd like to provide [all the options available to HTML5 push notifications](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification), right?

I really like the idea of allowing ember apps to configure all the possible `showNotification` options via `config/environment.js` as simple JSON.  However this does create the unfortunate drawback of automatically configuring all push notifications the same way.

I think we could mitigate this risk by overwriting the ember app configuration with the [individual notification settings from FCM](https://firebase.google.com/docs/cloud-messaging/http-server-ref#table2c) which I hope are not exhaustive, as there is way too few supported options documented.  Either way as Firebase rolls out better support for their web SDK, we may end up in a happy place.

Do you have any thoughts on this approach?

**Comment by alexmasita** [comment]
Precisely.

I think the `config/environment.js` approach is perfect.

Will try modifying your addon code in-app and share with you my implementation if you will not beat me to it.  

I also agree with you that overwriting the default ember app configuration will be the way to go so as to allow basic users to go with the default as currently is.  Super.
