### ISSUE TITLE
Break dependence on emberfire

### ISSUE THREAD

**Issue by alexmasita** [Matt-Jensen/ember-service-worker-emberfire-messaging#7]
Have recently abandoned `emberfire` adapter for the `ember-cloud-firestore-adapter`.  However it appears now an error is thrown to this effect:

```
Entry module not found: Error: Cannot resolve 'file' or 'directory' ./firebase-browser.js in /Users/alexmasita/External/Personal/projects/Ember Apps/mobile-services/tmp/webpack_writer-input_base_path-0YTavchN.tmp/0
resolve file
```
Will examine the code to see if I can create a pull request.

**Comment by alexmasita** [comment]
Hi Matt.  On second thought, maybe we should fork this and create a new repo for firestore?  This way, we do not end up making this chunkier than it needs to be.  Your thoughts?

**Comment by Matt-Jensen** [comment]
I agree forking this repo seems like the best route.

**Comment by alexmasita** [comment]
I am still having trouble figuring out what breaks the build when I install this addon.  I have tried to modify the parts that I think are throwing the error highlighted here which are changing all instances where the firebase service is called to as follows:

From this:
```
export default Service.extend({
  firebaseApp: service(),
```
To this:
```
export default Service.extend({
  firebase: service(),
```
The above should work because when you install `ember-cloud-firestore-adapter` the recommended way to get the raw firebase api is to install the firebase service addon called `ember-firebase-service` which makes firebase available as `firebase`.

Any guidance here @Matt-Jensen will be highly appreciated.

**Comment by Matt-Jensen** [comment]
Sorry @alexmasita I've never worked with either `ember-cloud-firestore-adapter` or `ember-firebase-service` before.  You have more experience than I do at this point.
